workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

default:
  tags:
    - docker-52-1-21
    - rust

fmt:
  script:
    - cargo fmt --all -- --check

clippy:
  script:
    - cargo clippy -- -D warnings
