workflow:
  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

default:
  tags:
    - docker-52-1-21
    - rust

.path-matrix:
  parallel:
    matrix:
      - PATH:
          - .
          - clients/actix

fmt:
  extends: .path-matrix
  script:
    - cd $PATH
    - cargo fmt --all -- --check

build:
  extends: .path-matrix
  script:
    - cd $PATH
    - cargo build --verbose

clippy:
  extends: .path-matrix
  script:
    - cd $PATH
    - cargo clippy -- -D warnings

test:
  extends: .path-matrix
  script:
    - cd $PATH
    - cargo test -- --nocapture
  timeout: 10 minutes
