[workspace]
resolver = "2"
members = [
    "clients/actix",
    "clients/actix/sample",
    "clients/axum",
    "clients/axum/sample",
    "clients/rocket",
    "clients/rocket/sample",
]

[workspace.dependencies]
nullnet-libappguard = { path = "../appguard-server/libappguard" }
