[package]
name = "appguard-clients-common"
publish = false
edition = "2021"

[dependencies]
tonic = { version = "0.12.3", features = ["tls", "tls-roots"] }
prost = "0.13.4"
tokio = { version = "1.10.0", default-features = false, features = ["time"] }

[build-dependencies]
tonic-build = "0.12.3"
