# Build:  docker build -f Dockerfile.fileserver -t fileserver .
# Run:    docker run --network none fileserver

FROM docker.io/svenstaro/miniserve:latest

COPY color /data/color

# EXPOSE 8080

CMD ["/data/color", "-p", "8080"]
