[package]
name = "sample"
publish = false
edition = "2021"

[dependencies]
appguard-axum = { path = ".."}
axum = "0.7.9"
axum-embed = "0.1.0"
rust-embed = "8.5.0"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
