[package]
name = "appguard-actix"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
nullnet-libappguard.workspace = true
appguard-client-authentication.workspace = true
actix-web = "4.9.0"
qstring = "0.7.2"
